### ISSUE TITLE
Need little help?

### ISSUE THREAD

**Issue by YasirAmeen** [lukaspili/Android-Reactive-Billing#7]
How can i check if the product is already purchased and how can i determine which product is purchased because i did not find any request code or any identity in Purchase flow.

**Comment by FireZenk** [comment]
You need to use: `.getPurchases(PurchaseType.PRODUCT, null)` they give you the list of products and if there are some purchased and pending for activation

**Comment by YasirAmeen** [comment]
@FireZenk Thank you for the reply, please tell me one more thing, Google base64 key is not available also there is no mention where to set, ?

**Comment by lukaspili** [comment]
See #8
