### ISSUE TITLE
Reactive Billing does not required Base64-encoded RSA public key ?

### ISSUE THREAD

**Issue by YasirAmeen** [lukaspili/Android-Reactive-Billing#8]
I am using the library, as documented in google that we need to add Base64 RSA public key when publish app with in App integration. Most of the library and google Trival Drive also need this, but i did not find where to add RSA key in this libraray.

**Comment by virusman** [comment]
Reactive-Billing doesn't validate purchases

**Comment by lukaspili** [comment]
The validation logic is specific to each application, and goes beyond the scope of this library.
The ```Purchase``` object provides the developerPayload that you can use to implement your own validation.
